using System.Collections.Generic;
namespace HealthDeptApp.Models
{
    public class HealthCodeGenerator {

        public class V {
            public V(int categoryId, string category, int position, string regulation)
            {
                CategoryId = categoryId;
                Category = category;
                Position = position;
                Regulation = regulation;
            }

            public int CategoryId { get; set; }
            public string Category { get; set; }
            public int Position { get; set; }
            public string Regulation { get; set; } 
        }    

        public static List<V> GetList() {
            return new List<V>(new [] {
            new V(1, "SUPERVISION", 01, "PERSON IN CHARGE PRESENT, DEMONSTRATES KNOWLEDGE, AND PERFORMS DUTIES"),
            new V(1, "SUPERVISION", 02, "CITY OF CHICAGO FOOD SERVICE SANITATION CERTIFICATE"),
            
            new V(2, "EMPLOYEE HEALTH", 03, "MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL EMPLOYEE; KNOWLEDGE, RESPONSIBILITIES AND REPORTING"),
            new V(2, "EMPLOYEE HEALTH", 04, "PROPER USE OF RESTRICTION AND EXCLUSION"),
            new V(2, "EMPLOYEE HEALTH", 05, "PROCEDURES FOR RESPONDING TO VOMITING AND DIARRHEAL EVENTS"),
            
            new V(3, "GOOD HYGIENIC PRACTICES", 06, "PROPER EATING, TASTING, DRINKING, OR TOBACCO USE"),
            new V(3, "GOOD HYGIENIC PRACTICES", 07, "NO DISCHARGE FROM EYES, NOSE, AND MOUTH"),

            new V(4, "PREVENTING CONTAMINATION BY HANDS", 08, "HANDS CLEAN & PROPERLY WASHED"),
            new V(4, "PREVENTING CONTAMINATION BY HANDS", 09, "NO BARE HAND CONTACT WITH RTE FOOD OR A PRE-APPROVED ALTERNATIVE PROCEDURE PROPERLY ALLOWED"),      
            new V(4, "PREVENTING CONTAMINATION BY HANDS", 10, "ADEQUATE HANDWASHING SINKS PROPERLY SUPPLIED AND ACCESSIBLE"),
            
            new V(5, "APPROVED SOURCE", 11, "FOOD OBTAINED FROM APPROVED SOURCE"),
            new V(5, "APPROVED SOURCE", 12, "FOOD RECEIVED AT PROPER TEMPERATURE"),
            new V(5, "APPROVED SOURCE", 13, "FOOD IN GOOD CONDITION, SAFE, & UNADULTERATED"),
            new V(5, "APPROVED SOURCE", 14, "REQUIRED RECORDS AVAILABLE: SHELLSTOCK TAGS, PARASITE DESTRUCTION"),
            
            new V(6, "PROTECTION FROM CONTAMINATION", 15, "FOOD SEPARATED AND PROTECTED"),
            new V(6, "PROTECTION FROM CONTAMINATION", 16, "FOOD-CONTACT SURFACES: CLEANED & SANITIZED"),
            new V(6, "PROTECTION FROM CONTAMINATION", 18, "PROPERT COOKING TIME & TEMPERATURE"),
            
            new V(7, "TIME/TEMPERATURE CONTROL FOR SAFETY", 19, "PROPER REHEATING PROCEDURES FOR HOT HOLDING"),
            new V(7, "TIME/TEMPERATURE CONTROL FOR SAFETY", 20, "PROPER COOLING TIME AND TEMPERATURE"),
            new V(7, "TIME/TEMPERATURE CONTROL FOR SAFETY", 21, "PROPER HOT HOLDING TEMPERATURES"),
            new V(7, "TIME/TEMPERATURE CONTROL FOR SAFETY", 22, "PROPER COLD HOLDING TEMPERATURES"),
            new V(7, "TIME/TEMPERATURE CONTROL FOR SAFETY", 23, "PROPER DATE MARKING AND DISPOSITION"),
            new V(7, "TIME/TEMPERATURE CONTROL FOR SAFETY", 24, "TIME AS A PUBLIC HEALTH CONTROL; PROCEEDURES & RECORDS"),
            
            new V(8, "CONSUMER ADVISORY", 25, "CONSUMER ADVISORY PROVIDED FOR RAW/UNDERCOOKED FOOD"),
            
            new V(9, "HIGHLY SUSCEPTIBLE POPULATIONS", 26, "PASTEURIZED FOODS USED; PROHIBITED FOODS NOT OFFERED"),
            
            new V(10, "FOOD/COLOR ADDITIVES AND TOXIC SUBSTANCES", 27, "FOOD ADDITIVES: APPROVED AND PROPERLY USED"),
            new V(10, "FOOD/COLOR ADDITIVES AND TOXIC SUBSTANCES", 28, "TOXIC SUBSTANCES PROPERLY IDENTIFIED, STORED, & USED"),
            
            new V(11, "CONFORMANCE WITH APPROVED PROCEDURES", 29, "COMPLIANCE WITH VARIANCE/SPECIALIZED PROCESS/HACCP"),
            
            new V(12, "SAFE FOOD AND WATER", 30, "PASTEURIZED EGGS USED WHERE REQUIRED"),
            new V(12, "SAFE FOOD AND WATER", 31, "WATER & ICE FROM APPROVED SOURCE"),
            new V(12, "SAFE FOOD AND WATER", 32, "VARIANCE OBTAINED FOR SPECIALIZED PROCESSING METHODS"),
            
            new V(13, "FOOD TEMPERATURE CONTROL", 33, "PROPER COOLING METHODS USED; ADEQUATE EQUIPMENT FOR TEMPERATURE CONTROL"),
            new V(13, "FOOD TEMPERATURE CONTROL", 34, "PLANT FOOD PROPERTY COOKED FOR HOT HOLDING"),
            new V(13, "FOOD TEMPERATURE CONTROL", 35, "APPROVED THAWING METHODS USED"),
            new V(13, "FOOD TEMPERATURE CONTROL", 36, "THERMOMETERS PROVIDED & ACCURATE"),
            
            new V(14, "FOOD IDENTIFICATION", 37, "FOOD PROPERLY LABELED; ORIGINAL CONTAINER"),
            
            new V(15, "PREVENTION OF FOOD CONTAMINATION", 38, "INSECTS, RODENTS, & ANIMALS NOT PRESENT"),
            new V(15, "PREVENTION OF FOOD CONTAMINATION", 39, "CONTAMINATION PREVENTED DURING FOOD PREPARATION, STORAGE & DISPLAY"),
            
            new V(16, "PREVENTION OF FOOD CONTAMINATION", 40, "PERSONAL CLEANLINESS"),
            new V(16, "PREVENTION OF FOOD CONTAMINATION", 41, "WIPING CLOTHS: PROPERLY USED & STORED"),
            new V(16, "PREVENTION OF FOOD CONTAMINATION", 42, "WASHING FRUITS & VEGETABLES"),
            
            new V(17, "PROPER USE OF UTENSILS", 43, "IN-USE UTENSILS: PROPERLY STORED"),
            new V(17, "PROPER USE OF UTENSILS", 44, "UTENSILS, EQUIPMENT & LINENS: PROPERLY STORED, DRIED, & HANDLED"),
            new V(17, "PROPER USE OF UTENSILS", 45, "SINGLE-USE/SINGLE-SERVICE ARTICLES: PROPERLY STORED & USED"),
            new V(17, "PROPER USE OF UTENSILS", 46, "GLOVES USED PROPERLY"),
            
            new V(18, "UTENSILS, EQUIPMENT, AND VENDING", 47, "FOOD & NON-FOOD CONTACT SURFACES CLEANABLE, PROPERLY DESIGNED, CONSTRUCTED & USED"),
            new V(18, "UTENSILS, EQUIPMENT, AND VENDING", 48, "WAREWASHING FACILITIES: INSTALLED, MAINTAINED & USED; TEST STRIPS"),
            new V(18, "UTENSILS, EQUIPMENT, AND VENDING", 49, "NON-FOOD/FOOD CONTACT SURFACES CLEAN"),

            new V(19, "PHYSICAL FACILITIES", 50, "HOT & COLD WATER AVAILABLE; ADEQUATE PRESSURE"),
            new V(19, "PHYSICAL FACILITIES", 51, "PLUMBING INSTALLED; PROPER BACKFLOW DEVICES"),
            new V(19, "PHYSICAL FACILITIES", 52, "SEWAGE & WASTE WATER PROPERLY DISPOSED"),
            new V(19, "PHYSICAL FACILITIES", 53, "TOILET FACILITIES: PROPERLY CONSTRUCTED, SUPPLIED, & CLEANED"),
            new V(19, "PHYSICAL FACILITIES", 54, "GARBAGE & REFUSE PROPERLY DISPOSED; FACILITIES MAINTAINED"),
            new V(19, "PHYSICAL FACILITIES", 55, "PHYSICAL FACILITIES INSTALLED, MAINTAINED & CLEAN"),
            new V(19, "PHYSICAL FACILITIES", 56, "ADEQUATE VENTILATION & LIGHTING; DESIGNATED AREAS USED"),
            
            new V(20, "EMPLOYEE TRAINING", 57, "ALL FOOD EMPLOYEES HAVE FOOD HANDLER TRAINING"),
            new V(20, "EMPLOYEE TRAINING", 58, "ALLERGEN TRAINING AS REQUIRED"),

            new V(21, "CITY OF CHICAGO ORDINANCE COMPLIANCE", 59, "PREVIOUS PRIORITY FOUNDATION VIOLATION CORRECTED"),
            new V(21, "CITY OF CHICAGO ORDINANCE COMPLIANCE", 60, "PREVIOUS CORE VIOLATION CORRECTED"),
            new V(21, "CITY OF CHICAGO ORDINANCE COMPLIANCE", 61, "SUMMARY REPORT DISPLAYED AND VISIBLE TO THE PUBLIC"),
            new V(21, "CITY OF CHICAGO ORDINANCE COMPLIANCE", 62, "COMPLIANCE WITH CLEAN INDOOR AIR ORDINANCE"),
            new V(21, "CITY OF CHICAGO ORDINANCE COMPLIANCE", 63, "REMOVAL OF SUSPENSION SIGN"),
            new V(21, "CITY OF CHICAGO ORDINANCE COMPLIANCE", 70, "NO SMOKING REGULATIONS")
            });
        }
    }
}